---
- name: apt-get update
  apt:
    update-cache: true
  tags:
    - updates

- name: apt upgrade
  apt:
    name: "*"
    state: latest
    force_apt_get: true
  tags:
    - updates

- name: Security
  import_tasks: security.yml
  tags:
    - security
