---
- name: SEC - Make a copy of security repos
  shell: cat /etc/apt/sources.list|grep secu >/etc/apt/security.sources.list

- name: SEC - Update cache
  apt: update_cache=yes

- name: SEC - Install security updates
  shell: apt-get upgrade -oDir::Etc::SourceList=/etc/apt/security.sources.list --force-yes -y
  args:
    warn: false
