---
- name: yum-plugin-security for release version 6
  yum:
      name: "yum-plugin-security"
      state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

- name: yum update
  yum:
      name: "*"
      state: latest
  tags:
      - updates

- name: yum security updates
  yum:
      name: "*"
      state: latest
      security: true
  tags:
      - security
