---
- name: yum update
  yum:
      name: "*"
      state: latest
  tags:
      - updates

- name: yum security updates
  yum:
      name: "*"
      state: latest
      security: true
  tags:
      - security
