---
- name: update the system 
  yum:
      name: "*"
      state: latest
  tags:
      - updates

- name: yum security updates
  yum:
      name: "*"
      state: latest
      security: yes
  tags:
      - security
